# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # You can use this variable in your frontend code (for example, via process.env.REACT_APP_BACKEND_URL)
      - REACT_APP_BACKEND_URL=http://backend:8080
